CREATE TABLE `experiment_runs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `run_id` varchar(128) NOT NULL,
  `scenario_id` varchar(256) NOT NULL,
  `scenario_hash` char(64) DEFAULT NULL,
  `condition_name` varchar(64) DEFAULT NULL,
  `stage` varchar(32) DEFAULT NULL,
  `run_mode` varchar(32) DEFAULT NULL,
  `corpus_hash` char(64) DEFAULT NULL,
  `corpus_version` varchar(128) DEFAULT NULL,
  `collection_name` varchar(256) DEFAULT NULL,
  `runtime_chain` varchar(64) DEFAULT NULL,
  `acceptance_status` varchar(32) DEFAULT NULL,
  `failure_reason` text DEFAULT NULL,
  `source_file` text DEFAULT NULL,
  `harness_version` varchar(128) DEFAULT NULL,
  `node_config_hash` char(64) DEFAULT NULL,
  `sc_policy_id` varchar(128) DEFAULT NULL,
  `policy_hash` char(64) DEFAULT NULL,
  `theta_source` varchar(128) DEFAULT NULL,
  `theta_locked` tinyint(4) NOT NULL DEFAULT 0,
  `started_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `run_id` (`run_id`),
  KEY `idx_experiment_runs_scenario` (`scenario_id`),
  KEY `idx_experiment_runs_condition` (`condition_name`),
  KEY `idx_experiment_runs_stage` (`stage`),
  KEY `idx_experiment_runs_runtime_chain` (`runtime_chain`),
  KEY `idx_experiment_runs_acceptance_status` (`acceptance_status`)
) ENGINE=InnoDB AUTO_INCREMENT=97 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `intervention_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `turn_node_log_id` bigint(20) NOT NULL,
  `rag_injected` tinyint(4) NOT NULL DEFAULT 0,
  `sc_policy_applied` tinyint(4) NOT NULL DEFAULT 0,
  `sc_policy_id` varchar(128) DEFAULT NULL,
  `policy_hash` char(64) DEFAULT NULL,
  `trigger_mode` varchar(128) DEFAULT NULL,
  `trigger_reasons` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`trigger_reasons`)),
  `trigger_eligible` tinyint(4) DEFAULT NULL,
  `trigger_source_nodes` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`trigger_source_nodes`)),
  `threshold_snapshot` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`threshold_snapshot`)),
  `previous_turn_used_for_trigger` int(11) DEFAULT NULL,
  `sc_triggered` tinyint(4) DEFAULT NULL,
  `sc_trigger_reason` varchar(512) DEFAULT NULL,
  `sc_trigger_rule_id` varchar(128) DEFAULT NULL,
  `sc_policy_anchor_chunk_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sc_policy_anchor_chunk_ids`)),
  `sc_evidence_sufficiency` varchar(64) DEFAULT NULL,
  `sc_response_mode` varchar(64) DEFAULT NULL,
  `sc_verification_required` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sc_verification_required`)),
  `sc_responsibility_boundary_applied` tinyint(4) DEFAULT NULL,
  `sc_decision_payload` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`sc_decision_payload`)),
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_intervention_turn_node` (`turn_node_log_id`),
  KEY `idx_intervention_policy_hash` (`policy_hash`),
  CONSTRAINT `fk_intervention_turn_node` FOREIGN KEY (`turn_node_log_id`) REFERENCES `turn_node_logs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8569 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `metric_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `turn_node_log_id` bigint(20) NOT NULL,
  `lms_value` double DEFAULT NULL,
  `lms_token_count` int(11) DEFAULT NULL,
  `theta_entropy` double DEFAULT NULL,
  `lms_delta` double DEFAULT NULL,
  `cds` double DEFAULT NULL,
  `ma_assert` double DEFAULT NULL,
  `ma_epist` double DEFAULT NULL,
  `ma_hedge` double DEFAULT NULL,
  `sent_count` int(11) DEFAULT NULL,
  `srr` double DEFAULT NULL,
  `sci` double DEFAULT NULL,
  `metrics_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metrics_json`)),
  `metric_status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metric_status`)),
  `quality_gate` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`quality_gate`)),
  `generation_quality_ready` tinyint(4) DEFAULT NULL,
  `analysis_eligible` tinyint(4) DEFAULT NULL,
  `exclude_from_causal_trigger` tinyint(4) DEFAULT NULL,
  `metric_trigger_eligibility` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metric_trigger_eligibility`)),
  `usable_as_quality_outcome` tinyint(4) DEFAULT NULL,
  `metric_pipeline_version` varchar(128) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_metric_turn_node` (`turn_node_log_id`),
  CONSTRAINT `fk_metric_turn_node` FOREIGN KEY (`turn_node_log_id`) REFERENCES `turn_node_logs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8569 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payload_audit_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `turn_node_log_id` bigint(20) NOT NULL,
  `prompt_hash` char(64) NOT NULL,
  `payload_hash` char(64) DEFAULT NULL,
  `message_count` int(11) DEFAULT NULL,
  `prompt_chars` int(11) DEFAULT NULL,
  `final_prompt_chars` int(11) DEFAULT NULL,
  `rag_context_chars` int(11) DEFAULT NULL,
  `sc_block_chars` int(11) DEFAULT NULL,
  `sc_block_hash` char(64) DEFAULT NULL,
  `prompt_contains_sc_marker` tinyint(4) DEFAULT NULL,
  `retrieved_chunk_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`retrieved_chunk_ids`)),
  `retrieved_chunk_ids_hash` char(64) DEFAULT NULL,
  `collection_name` varchar(256) DEFAULT NULL,
  `corpus_version` varchar(128) DEFAULT NULL,
  `history_window_turns_configured` int(11) DEFAULT NULL,
  `history_turns_used` int(11) DEFAULT NULL,
  `rag_injected` tinyint(4) NOT NULL DEFAULT 0,
  `sc_policy_applied` tinyint(4) NOT NULL DEFAULT 0,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payload_turn_node` (`turn_node_log_id`),
  KEY `idx_payload_prompt_hash` (`prompt_hash`),
  CONSTRAINT `fk_payload_turn_node` FOREIGN KEY (`turn_node_log_id`) REFERENCES `turn_node_logs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_payload_flags_boolean` CHECK (`rag_injected` in (0,1) and `sc_policy_applied` in (0,1))
) ENGINE=InnoDB AUTO_INCREMENT=8569 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `rag_retrieval_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `turn_node_log_id` bigint(20) NOT NULL,
  `sc_policy_applied` tinyint(4) NOT NULL DEFAULT 0,
  `query_hash` char(64) NOT NULL,
  `collection_name` varchar(256) DEFAULT NULL,
  `top_k` int(11) DEFAULT NULL,
  `returned_count` int(11) DEFAULT NULL,
  `rag_context_chars` int(11) DEFAULT NULL,
  `retrieval_method` varchar(64) DEFAULT NULL,
  `table_exposure` tinyint(4) DEFAULT NULL,
  `retrieved_chunk_ids` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`retrieved_chunk_ids`)),
  `retrieved_chunk_ids_hash` char(64) DEFAULT NULL,
  `chunk_lengths` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`chunk_lengths`)),
  `block_type_distribution` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`block_type_distribution`)),
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_rag_turn_node` (`turn_node_log_id`),
  KEY `idx_rag_query_hash` (`query_hash`),
  CONSTRAINT `fk_rag_turn_node` FOREIGN KEY (`turn_node_log_id`) REFERENCES `turn_node_logs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3389 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `turn_node_logs` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `experiment_run_id` bigint(20) NOT NULL,
  `turn_no` int(11) NOT NULL,
  `node` varchar(8) NOT NULL,
  `node_role` varchar(32) DEFAULT NULL,
  `physical_node_url` varchar(255) DEFAULT NULL,
  `utterance_hash` char(64) NOT NULL,
  `response_text` mediumtext DEFAULT NULL,
  `response_hash` char(64) DEFAULT NULL,
  `elapsed_ms` double DEFAULT NULL,
  `model_name` varchar(128) DEFAULT NULL,
  `model_digest` varchar(256) DEFAULT NULL,
  `temperature` double DEFAULT NULL,
  `seed` int(11) DEFAULT NULL,
  `thinking_disabled_requested` tinyint(4) NOT NULL DEFAULT 1,
  `endpoint_mode` varchar(64) DEFAULT NULL,
  `response_text_raw_hash` char(64) DEFAULT NULL,
  `thinking_tag_present` tinyint(4) DEFAULT NULL,
  `empty_thinking_shell` tinyint(4) DEFAULT NULL,
  `thinking_content_present` tinyint(4) DEFAULT NULL,
  `cleaning_applied` tinyint(4) DEFAULT NULL,
  `cleaning_allowed` tinyint(4) DEFAULT NULL,
  `failed_TR` tinyint(4) DEFAULT NULL,
  `removed_prefix_chars` int(11) DEFAULT NULL,
  `raw_logprobs_len` int(11) DEFAULT NULL,
  `clean_logprobs_len` int(11) DEFAULT NULL,
  `excluded_token_positions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`excluded_token_positions`)),
  `quality_gate` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`quality_gate`)),
  `generation_quality_ready` tinyint(4) DEFAULT NULL,
  `analysis_eligible` tinyint(4) DEFAULT NULL,
  `exclude_from_causal_trigger` tinyint(4) DEFAULT NULL,
  `history_eligible` tinyint(4) DEFAULT NULL,
  `history_exclusion_reason` varchar(512) DEFAULT NULL,
  `usable_as_quality_outcome` tinyint(4) DEFAULT NULL,
  `metric_status` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metric_status`)),
  `metric_trigger_eligibility` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metric_trigger_eligibility`)),
  `metrics_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`metrics_json`)),
  `raw_response_keys` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`raw_response_keys`)),
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_turn_node` (`experiment_run_id`,`turn_no`,`node`),
  KEY `idx_turn_node_run_turn` (`experiment_run_id`,`turn_no`),
  KEY `idx_turn_node_node` (`node`),
  KEY `idx_turn_node_role` (`node_role`),
  CONSTRAINT `fk_turn_node_experiment_run` FOREIGN KEY (`experiment_run_id`) REFERENCES `experiment_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `chk_turn_node_node` CHECK (`node` in ('A','B','C'))
) ENGINE=InnoDB AUTO_INCREMENT=8569 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
